"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/f7zvLz2m10g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Badge } from "@/app/item/ui/badge"
import { CardContent, Card } from "@/app/item/ui/card"
import { gql, useQuery } from "@apollo/client";

const GET_ITEMS = gql`
query getItems {
  item {
    id
    image
    name
    price
    size_options
    updated_at
    desc
    created_at
    color_options
  }
}
`
export default function Item() {

  const {data} = useQuery(GET_ITEMS);
const items = data?.item;
console.log(items);

// {items.map(t:any) => 아래 html 소스와 바인딩}

  return (
    <div className="grid grid-cols-4 gap-4">
      {items?.map((item:any) => (
              <Card className="w-[250px]"
              key={item.id}
              >
        <img
          alt="product image"
          className="w-full h-auto"
          height="180"
          src={item.image}
          style={{
            aspectRatio: "250/180",
            objectFit: "cover",
          }}
          width="250"
        />
        <CardContent className="space-y-2 p-4">
          <h2 className="text-lg font-medium"></h2>
          <p className="text-sm">{item.name}</p>
          <div className="space-y-2">
            <p className="text-sm line-through">{item.price}</p>
            <p className="text-lg font-semibold">75,150원</p>
            <Badge className="px-2 py-1 text-sm" variant="secondary">
              41%
            </Badge>
          </div>
        </CardContent>
      </Card>
      ))}

     
      <Card className="w-[250px]">
        <img
          alt="product image"
          className="w-full h-auto"
          height="180"
          src="/placeholder.svg"
          style={{
            aspectRatio: "250/180",
            objectFit: "cover",
          }}
          width="250"
        />
        <CardContent className="space-y-2 p-4">
          <h2 className="text-lg font-medium">오아</h2>
          <p className="text-sm">오아 이360 바닥 미니마사지기 어깨기</p>
          <div className="space-y-2">
            <p className="text-sm line-through">199,000원</p>
            <p className="text-lg font-semibold">156,600원</p>
            <Badge className="px-2 py-1 text-sm" variant="secondary">
              21%
            </Badge>
          </div>
        </CardContent>
      </Card>
      <Card className="w-[250px]">
        <img
          alt="product image"
          className="w-full h-auto"
          height="180"
          src="/placeholder.svg"
          style={{
            aspectRatio: "250/180",
            objectFit: "cover",
          }}
          width="250"
        />
        <CardContent className="space-y-2 p-4">
          <h2 className="text-lg font-medium">기타</h2>
          <p className="text-sm">[전통주] 화개 20ml x32병 (16병x2세트)</p>
          <div className="space-y-2">
            <p className="text-sm line-through">71,900원</p>
            <p className="text-lg font-semibold">61,110원</p>
            <Badge className="px-2 py-1 text-sm" variant="secondary">
              15%
            </Badge>
          </div>
        </CardContent>
      </Card>
      <Card className="w-[250px]">
        <img
          alt="product image"
          className="w-full h-auto"
          height="180"
          src="/placeholder.svg"
          style={{
            aspectRatio: "250/180",
            objectFit: "cover",
          }}
          width="250"
        />
        <CardContent className="space-y-2 p-4">
          <h2 className="text-lg font-medium">오아</h2>
          <p className="text-sm">오아 손톱해초소 산 마사지기 어깨기</p>
          <div className="space-y-2">
            <p className="text-sm line-through">89,000원</p>
            <p className="text-lg font-semibold">74,000원</p>
            <Badge className="px-2 py-1 text-sm" variant="secondary">
              17%
            </Badge>
          </div>
        </CardContent>
      </Card>
    </div>
  )

}
